version: '2'
services:
  proxy:
    privileged: true
    image: theskyinflames/dockerized-proxy
    environment:
      - PROXY_OPTS=-l :4002 -r externos.hotetec.com:80 -c -vv
    ports:
      - 8998:4002
